on:
  workflow_call:
    inputs:
     container_name:
        description: The name of the container to release a package as.
        required: false
        type: string
        default: ${{ github.repository }}
     container_tag:
       description: The name of the container to release a package as.
       required: false
       type: string
       default: ${{ github.sha }}


jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/guidion-digital
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build and push
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          push: true
          tags: |
            ghcr.io/${{ inputs.container_name }}:${{ inputs.container_tag }}
